# This is a basic workflow to help you get started with Actions

name: Build on Platform

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_call:
    inputs:
      runner:
        description: "The runner to use"
        required: true
        type: string
        
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test-javascript:
    runs-on: ${{ inputs.runner }}

    steps:
      - run: echo Testing Javascript

  build-3rdparty:
    runs-on: ${{ inputs.runner }}
    
    steps:
      - run: echo Build 3rdparty

  test-python:
    runs-on: ${{ inputs.runner }}
    
    if: ${{ !startsWith(inputs.runner, 'windows') }}

    needs:
      - build-3rdparty
      
    steps:
      - run: echo Testing Python

  build-cpp:
    # The type of runner that the job will run on
    runs-on: ${{ inputs.runner }}

    needs:
      - build-3rdparty

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - run: echo Build

  test-cpp:
    runs-on: ${{ inputs.runner }}

    needs:
      - build-cpp
      
    steps:
      - run: echo Testing Python

  test-results:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    if: ${{ !startsWith(inputs.runner, 'windows') }}

    needs:
      - test-javascript
      - test-python
      - test-cpp

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - run: echo Publishing test results

  test-results-windows:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    if: ${{ startsWith(inputs.runner, 'windows') }}

    needs:
      - test-javascript
      - test-cpp

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - run: echo Publishing test results

  packaging:
    # The type of runner that the job will run on
    runs-on: ${{ inputs.runner }}

    if: ${{ !startsWith(inputs.runner, 'windows') }}

    needs:
      - test-javascript
      - test-python
      - build-cpp

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - run: echo Packaging

  packaging-windows:
    # The type of runner that the job will run on
    runs-on: ${{ inputs.runner }}

    if: ${{ startsWith(inputs.runner, 'windows') }}

    needs:
      - test-javascript
      - build-cpp

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - run: echo Packaging
