# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch
        

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-3rdparty:
    runs-on: ubuntu-latest
    
    steps:
      - run: echo Build 3rdparty
  
  test:
    runs-on: ubuntu-latest

    needs:
      - build-3rdparty
      
    steps:
      - run: echo Testing

  test-results:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    needs:
      - test

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - run: echo Publishing test results

  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    needs:
      - test

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - run: echo Build

  packaging:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    needs:
      - build

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - run: echo Packaging
