# This is a basic workflow to help you get started with Actions

name: Master

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:    
    
  # This workflow contains a single job called "build"
  build:
    strategy:
      fail-fast: false
      matrix: 
        runner: [ubuntu-latest, windows-latest]
        

    # The type of runner that the job will run on
    runs-on: ${{ matrix.runner }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Build on ${{ matrix.runner }}
        run: |
          echo "Run on ${{ matrix.runner }}
