# This is a basic workflow to help you get started with Actions

name: Master

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  pre-build:
    runs-on: ubuntu-latest
    
    steps:
      - run: echo "Do some preparation"
    
  # This workflow contains a single job called "build"
  build:
    strategy:
      fail-fast: false
      matrix: 
        runner: [ubuntu-latest, windows-latest, macos-latest]
    
    needs: pre-build

    uses: ./.github/workflows/manual.yml
    with:
      runner: ${{ matrix.runner }}
    
  upload-packages:
    runs-on: ubuntu-latest
    
    needs: 
      - build
    
    steps:
      - run: echo "upload packages"

